---
- name: Full Configuration of LAB-SW Cisco Switch
  hosts: all_devices
  gather_facts: no
  connection: network_cli
  serial: 1

  tasks:

    - name: Set hostname,user
      cisco.ios.ios_config:
        lines:
          - hostname {{inventory_hostname}}
        save_when: changed

    - name: Configure VLANs
      cisco.ios.ios_config:
        parents: "vlan {{ item.vlan_id }}"
        lines:
          - name {{ item.vlan_name }}
      loop:
        - { vlan_id: 700, vlan_name: "auto_700" }
        - { vlan_id: 800, vlan_name: "auto_800" }
        - { vlan_id: 900, vlan_name: "auto_900" }


    - name: configuring L3 vlan for 700,800,900
      cisco.ios.ios_config:
        parents: "interface vlan {{item.num}}"
        lines:
          - description {{item.desc}}
          - ip address {{item.ip}} {{item.mask}}
          - no shutdown
      loop:
        - { num: 700, desc: "L3_700", ip: "10.1.1.1", mask: "255.255.255.0"}
        - { num: 800, desc: "L3_800", ip: "10.1.2.1", mask: "255.255.255.0"}
        - { num: 900, desc: "L3_900", ip: "10.1.3.1", mask: "255.255.255.0"}


    - name: Save configuration
      cisco.ios.ios_config:
        save_when: always
